version: '3.8'

services:
  220009456-web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - 220009456-db
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  220009456-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 220009456_shareride_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  220009456-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 220009456-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - 220009456-db

volumes:
  db_data: